name: Razor7 Monitor

on:
  schedule:
    - cron: "*/2 * * * *"   # Toutes les 2 minutes
  workflow_dispatch:        # Pour lancer manuellement
  push:
    paths:
      - "last_tip.txt"

jobs:
  check_razor7:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tip checker
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python check_tip.py

      - name: Commit updated last_tip.txt
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add last_tip.txt
          git commit -m "update last seen tip" || echo "No changes"
          git push || echo "No changes to push"
